use employee ;
select * FROM EMPLOYEE ;

ALTER TABLE EMPLOYEE ADD constraint CH_EMAIL 
CHECK(EMAIL  LIKE '%@GMAIL.COM');

ALTER TABLE EMPLOYEE DROP COLUMN EMAIL ;

ALTER TABLE EMPLOYEE ADD COLUMN 
EMAIL VARCHAR(50) NOT NULL,
ADD constraint CH_EMAIL CHECK(EMAIL LIKE '%@GMAIL.COM');


SELECT * FROM EMPLOYEE ;

UPDATE EMPLOYEE SET EMAIL = 'SARTHAK@YAHOO.COM' 
WHERE EMPLOYEEID = 2 ; 

UPDATE EMPLOYEE SET EMAIL = 'SARTHAK.SHARMA@GMAIL.COM' 
WHERE EMPLOYEEID = 2 ; 

describe EMPLOYEE ;
DESCRIBE DEPARTMENT ;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK 
foreign key(DEPARTMENTID) references
DEPARTMENT(DEPARTMENTID) ON DELETE CASCADE ;

ALTER TABLE EMPLOYEE DROP PRIMARY KEY ;

DESCRIBE EMPLOYEE ;

ALTER TABLE EMPLOYEE DROP foreign key FK ;

insert into employee(employeeid,firstname,lastname , email,departmentid) 
values(6,'seeta1' ,'kumari1','seeta@GMAIL.com' ,4);

insert into employee(employeeid,firstname,lastname , email,departmentid) 
values(7,'seeta2' ,'kumari2','seetaKUMARI@GMAIL.com' ,7);


SELECT * FROM DEPARTMENT ;


-- SET DEFAULT SALARY 25000

describe employee ;

ALTER TABLE EMPLOYEE MODIFY SALary DECIMAL(10,3)
 CHECK(SALARY>25000);

ALTER TABLE EMPLOYEE MODIFY SALary DECIMAL(10,3)
 DEFAULT(SALARY=25000) ;

SELECT * FROM employee ;

INSERT INTO EMPLOYEE 
VALUES (4,'raman1','verma',
'raman1@gmail.com',	1,40000,	'2023-01-01');

INSERT INTO EMPLOYEE VALUES 
(4,'raman2','verma2','raman12@gmail.com',1,4000,
	'2023-01-01');
    
ALTER TABLE employee MODIFY FIRSTNAME VARCHAR(50) FIRST ;

ALTER TABLE employee MODIFY LASTNAME VARCHAR(50)
 AFTER FIRSTNAME;


SELECT * FROM EMPLOYEE ;



