USE STARTUP1 ; 

SELECT * FROM 50_STARTUPS ; 

RENAME TABLE 50_STARTUPS TO STARTUP ;

-- SELECT STATE AND RND 

SELECT STATE , RND  FROM STARTUP ;

-- SELECT 5 OBSERVATIONS FROM STATE AND rnd

SELECT STATE , RND  FROM STARTUP LIMIT 5;

-- SELECT 5 OBSERVATIONS FROM STATE AND rnd FROM 2ND

SELECT 
    STATE, RND
FROM
    STARTUP
LIMIT 5 OFFSET 1; 


-- SELECT ADMIN COST AND STATE FLORIDA

SELECT 
    STATE, ADMIN
FROM
    STARTUP
WHERE
    STATE = 'FLORIDA';



/*SELECT PROFIT  AND STATE FLORIDA
 WHERE PROFIT >25000 */
 
SELECT 
    PROFIT, STATE
FROM
    STARTUP
WHERE
    STATE = 'FLORIDA' AND PROFIT > 25000;



SELECT 
    PROFIT, STATE
FROM
    STARTUP
WHERE
    STATE = 'FLORIDA' AND PROFIT > 25000 
    LIMIT 5 OFFSET 4;
    
/* SELECT STATE WHERE 
STATE = CALIFORNIA OR NEW YORK */

/*SELECT STATE WHERE 
STATE = CALIFORNIA OR NEW YORK*/


SELECT 
    state
FROM
    startup
WHERE
    state = 'california' 
    OR state ='new york';

/* SELECT 5 STATE WHERE 
PROFIT BETWEEN 5000 AND 2500 */

SELECT STATE ,PROFIT FROM STARTUP WHERE 
PROFIT >5000 AND PROFIT <25000 ;

SELECT STATE ,PROFIT FROM STARTUP WHERE 
PROFIT BETWEEN 5000 AND 192261.83 ;


 /* SELECT 5 STATE WHERE 
PROFIT IN 5000 AND 25000 */

SELECT * FROM STARTUP LIMIT 5 ;

SELECT STATE ,PROFIT FROM STARTUP WHERE 
PROFIT IN (5000 ,25000 ,192261.83,191792.06) ;


-- SELECT STATE WITH INITIAL CHARACTER 'A'

SELECT 
    STATE
FROM
    STARTUP
WHERE
    STATE LIKE 'A%';

-- SELECT STATE WITH 2ND CHARACTER 'A';

/* SELECT DATA FROM 
STARTUP WHERE STATE = NEWYORK 
OR CALIFORNIA' AND PROFIT >35000 */


SELECT 
    state
FROM
    startup
WHERE
    state = 'New York'
        OR state = 'California' AND profit > 35000;
        
        
        
        
        